### ISSUE TITLE
Captures issues

### ISSUE THREAD

**Issue by sanandrea** [orchestrated-io/artillery-engine-lambda#21]
Stack trace

```
Test run id: tbghj_9ecx5axregh5qfjg3nqfn4p3wq4p8_6tpd
⠇ (node:27194) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Phase started: unnamed (index: 0, duration: 1s) 13:09:43(+0000)

⠦ worker error, id: 1 Error [TypeError]: Cannot read properties of null (reading 'captures')
    at captured (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/index.js:188:56)
    at Object.captureOrMatch (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/artillery/core/lib/engine_util.js:375:12)
    at Response.<anonymous> (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/index.js:182:21)
    at Request.<anonymous> (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/aws-sdk/lib/request.js:367:18)
    at Request.callListeners (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /local/home/cccc/.nvm/versions/node/v16.20.0/lib/node_modules/artillery-engine-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10 {
  code: 'TypeError',
  time: 2023-06-19T13:09:44.362Z
}

```

My config:
```
config:
  target: "MyFun"
  lambda:
    region: "us-west-2"
  phases:
    - arrivalCount: 10
      duration: 1
  engines:
    lambda: {}

scenarios:
  - name: "Invoke function"
    engine: "lambda"
    flow:
      - loop:
        - invoke:
           # data may be a string or an object. Objects
           # will be JSON.stringified.
           clientContext: '{"app": "MyApp"}'
           invocationType: "Event"
           logType: "Tail"
           payload: '{"Some payload":"asdfasf"}'
           qualifier: "1"
        - think: 1
        count: 100
```
